# Usage:
#       export BASE_DIR=~/git/MakeSystem
#       make [BUILD_TYPE=Debug] [VERBOSE=1]

include $(BASE_DIR)/Build/Config/Config.mk

TARGET   := Sub00.a
SRCS     := Sub00.cpp
INCS     :=
DEFS     :=
SUB_DIRS :=
LIBS     :=

include $(BASE_DIR)/Build/Config/Build.mk
